// <auto-generated />
using System;
using Bookstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookstore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107012739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bobsusedbookstore_dbo")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("IsActive")
                        .HasColumnType("integer")
                        .HasColumnName("is_active");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("address", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.Authors.Author", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("business_entity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BusinessEntityID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("gender");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job_title");

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("login_id");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("marital_status");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("NationalIDNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("national_id_number");

                    b.Property<short>("VacationHours")
                        .HasColumnType("smallint")
                        .HasColumnName("vacation_hours");

                    b.HasKey("BusinessEntityID");

                    b.ToTable("author", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<int>("BookTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("book_type_id");

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isbn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer")
                        .HasColumnName("publisher_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("BookTypeId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("book", "bobsusedbookstore_dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Li Juan",
                            BookTypeId = 1,
                            ConditionId = 5,
                            CoverImageUrl = "/images/coverimages/apocalypse.png",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8625),
                            GenreId = 13,
                            ISBN = "6556784356",
                            Name = "2020: The Apocalypse",
                            Price = 10.95m,
                            PublisherId = 15,
                            Quantity = 25,
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8626)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nikki Wolf",
                            BookTypeId = 1,
                            ConditionId = 6,
                            CoverImageUrl = "/images/coverimages/childrenofiron.png",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8632),
                            GenreId = 11,
                            ISBN = "7665438976",
                            Name = "Children Of Iron",
                            Price = 13.95m,
                            PublisherId = 16,
                            Quantity = 3,
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8632)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Richard Roe",
                            BookTypeId = 1,
                            ConditionId = 5,
                            CoverImageUrl = "/images/coverimages/goldinthedark.png",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8634),
                            GenreId = 13,
                            ISBN = "5442280765",
                            Name = "Gold In The Dark",
                            Price = 6.50m,
                            PublisherId = 17,
                            Quantity = 10,
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8635)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Pat Candella",
                            BookTypeId = 2,
                            ConditionId = 7,
                            CoverImageUrl = "/images/coverimages/leaguesofsmoke.png",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8640),
                            GenreId = 11,
                            ISBN = "4556789542",
                            Name = "Leagues Of Smoke",
                            Price = 3m,
                            PublisherId = 18,
                            Quantity = 1,
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8641)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Carlos Salazar",
                            BookTypeId = 2,
                            ConditionId = 5,
                            CoverImageUrl = "/images/coverimages/alonewiththestars.png",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8643),
                            GenreId = 12,
                            ISBN = "4563358087",
                            Name = "Alone With The Stars",
                            Price = 15.95m,
                            PublisherId = 19,
                            Quantity = 5,
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8643)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Terri Whitlock",
                            BookTypeId = 1,
                            ConditionId = 6,
                            CoverImageUrl = "/images/coverimages/girlinthepolaroid.png",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8645),
                            GenreId = 12,
                            ISBN = "2354435678",
                            Name = "The Girl In The Polaroid",
                            Price = 8.25m,
                            PublisherId = 20,
                            Quantity = 2,
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8646)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mary Major",
                            BookTypeId = 2,
                            ConditionId = 5,
                            CoverImageUrl = "/images/coverimages/1001jokes.png",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8648),
                            GenreId = 11,
                            ISBN = "6554789632",
                            Name = "1001 Jokes",
                            Price = 13.95m,
                            PublisherId = 21,
                            Quantity = 7,
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8648)
                        },
                        new
                        {
                            Id = 8,
                            Author = "Mateo Jackson",
                            BookTypeId = 3,
                            ConditionId = 7,
                            CoverImageUrl = "/images/coverimages/mysearchformeaning.png",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8650),
                            GenreId = 8,
                            ISBN = "4558786554",
                            Name = "My Search For Meaning",
                            Price = 5m,
                            PublisherId = 22,
                            Quantity = 15,
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8651)
                        });
                });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.ToTable("shopping_cart", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_cart_id");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<int>("WantToBuy")
                        .HasColumnType("integer")
                        .HasColumnName("want_to_buy");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("shopping_cart_item", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Sub")
                        .IsUnique();

                    b.ToTable("customer", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book_name");

                    b.Property<decimal>("BookPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("book_price");

                    b.Property<int>("BookTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("book_type_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("FrontUrl")
                        .HasColumnType("text")
                        .HasColumnName("front_url");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isbn");

                    b.Property<int>("OfferStatus")
                        .HasColumnType("integer")
                        .HasColumnName("offer_status");

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer")
                        .HasColumnName("publisher_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("BookTypeId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("offer", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("order_status");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("order", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_item", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.Products.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("name");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("product_number");

                    b.Property<int>("SafetyStockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("safety_stock_level");

                    b.HasKey("ProductID");

                    b.ToTable("product", "bobsusedbookstore_dbo");
                });

            modelBuilder.Entity("Bookstore.Domain.ReferenceData.ReferenceDataItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.ToTable("reference_data", "bobsusedbookstore_dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8243),
                            DataType = 2,
                            Text = "Hardcover",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8248)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8251),
                            DataType = 2,
                            Text = "Trade Paperback",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8251)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8253),
                            DataType = 2,
                            Text = "Mass Market Paperback",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8253)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8254),
                            DataType = 1,
                            Text = "New",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8255)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8256),
                            DataType = 1,
                            Text = "Like New",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8257)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8258),
                            DataType = 1,
                            Text = "Good",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8259)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8260),
                            DataType = 1,
                            Text = "Acceptable",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8261)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8262),
                            DataType = 3,
                            Text = "Biographies",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8263)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8264),
                            DataType = 3,
                            Text = "Children's Books",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8265)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8266),
                            DataType = 3,
                            Text = "History",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8267)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8268),
                            DataType = 3,
                            Text = "Literature & Fiction",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8269)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8270),
                            DataType = 3,
                            Text = "Mystery, Thriller & Suspense",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8270)
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8272),
                            DataType = 3,
                            Text = "Science Fiction & Fantasy",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8272)
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8273),
                            DataType = 3,
                            Text = "Travel",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8274)
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8275),
                            DataType = 0,
                            Text = "Arcadia Books",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8276)
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8277),
                            DataType = 0,
                            Text = "Astral Publishing",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8278)
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8279),
                            DataType = 0,
                            Text = "Moonlight Publishing",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8279)
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8281),
                            DataType = 0,
                            Text = "Dreamscape Press",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8281)
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8282),
                            DataType = 0,
                            Text = "Enchanted Library",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8283)
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8284),
                            DataType = 0,
                            Text = "Fantasia House",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8285)
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8286),
                            DataType = 0,
                            Text = "Horizon Books",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8287)
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8288),
                            DataType = 0,
                            Text = "Infinity Press",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8289)
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8290),
                            DataType = 0,
                            Text = "Paradigm Publishing",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8290)
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8292),
                            DataType = 0,
                            Text = "Aurora Publishing",
                            UpdatedOn = new DateTime(2025, 11, 7, 1, 27, 38, 357, DateTimeKind.Utc).AddTicks(8292)
                        });
                });

            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
                {
                    b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
                {
                    b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                        .WithMany()
                        .HasForeignKey("BookTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookType");

                    b.Navigation("Condition");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
                {
                    b.HasOne("Bookstore.Domain.Books.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.Carts.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
                {
                    b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                        .WithMany()
                        .HasForeignKey("BookTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookType");

                    b.Navigation("Condition");

                    b.Navigation("Customer");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
                {
                    b.HasOne("Bookstore.Domain.Addresses.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("Bookstore.Domain.Books.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.Domain.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
