//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreBackend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookstoreBackend.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveLabel {
            get {
                return ResourceManager.GetString("ActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Info.
        /// </summary>
        public static string AddressInfoLabel {
            get {
                return ResourceManager.GetString("AddressInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders.
        /// </summary>
        public static string AllOrdersLabel {
            get {
                return ResourceManager.GetString("AllOrdersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveButton {
            get {
                return ResourceManager.GetString("ApproveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Picture.
        /// </summary>
        public static string BackPictureLabel {
            get {
                return ResourceManager.GetString("BackPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Selling Book.
        /// </summary>
        public static string BestSellerBookLabel {
            get {
                return ResourceManager.GetString("BestSellerBookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Selling Format.
        /// </summary>
        public static string BestSellerFormatLabel {
            get {
                return ResourceManager.GetString("BestSellerFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Selling Genre.
        /// </summary>
        public static string BestSellerGenreLabel {
            get {
                return ResourceManager.GetString("BestSellerGenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Selling Publisher.
        /// </summary>
        public static string BestSellerPublisherLabel {
            get {
                return ResourceManager.GetString("BestSellerPublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Id.
        /// </summary>
        public static string BookIdLabel {
            get {
                return ResourceManager.GetString("BookIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name.
        /// </summary>
        public static string BookNameLabel {
            get {
                return ResourceManager.GetString("BookNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Find Book Click Here.
        /// </summary>
        public static string BookNotFoundMessage {
            get {
                return ResourceManager.GetString("BookNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Order.
        /// </summary>
        public static string CancelOrderMessage {
            get {
                return ResourceManager.GetString("CancelOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that no search results have been returned. Try changing your search query or the filter category.
        /// </summary>
        public static string ChangeQueryMessage {
            get {
                return ResourceManager.GetString("ChangeQueryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File....
        /// </summary>
        public static string ChooseFileField {
            get {
                return ResourceManager.GetString("ChooseFileField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string ConditionLabel {
            get {
                return ResourceManager.GetString("ConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t find in the list ? Add New Condition.
        /// </summary>
        public static string ConditionNotFoundLabel {
            get {
                return ResourceManager.GetString("ConditionNotFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Shipment.
        /// </summary>
        public static string ConfirmShipmentButton {
            get {
                return ResourceManager.GetString("ConfirmShipmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-upload the photos as they violate one or more of our content policies.
        /// </summary>
        public static string CoverPhotoViolateErrorMessage {
            get {
                return ResourceManager.GetString("CoverPhotoViolateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Pictures Gallery.
        /// </summary>
        public static string CoverPictureMessage {
            get {
                return ResourceManager.GetString("CoverPictureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string CustomerIdLabel {
            get {
                return ResourceManager.GetString("CustomerIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Info.
        /// </summary>
        public static string CustomerInfoLabel {
            get {
                return ResourceManager.GetString("CustomerInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerNameLabel {
            get {
                return ResourceManager.GetString("CustomerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the search query.
        /// </summary>
        public static string EnterSearchQueryMessage {
            get {
                return ResourceManager.GetString("EnterSearchQueryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error has occurred. Please refresh the page or go back to the previous page.
        /// </summary>
        public static string ErrorPageMessage {
            get {
                return ResourceManager.GetString("ErrorPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Delivery Date.
        /// </summary>
        public static string ExpectedDeliveryDateLabel {
            get {
                return ResourceManager.GetString("ExpectedDeliveryDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        public static string FilterByLabel {
            get {
                return ResourceManager.GetString("FilterByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string FormatLabel {
            get {
                return ResourceManager.GetString("FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Picture.
        /// </summary>
        public static string FrontPictureLabel {
            get {
                return ResourceManager.GetString("FrontPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string GenreLabel {
            get {
                return ResourceManager.GetString("GenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t find in the list ? Add New Genre.
        /// </summary>
        public static string GenreNotFoundLabel {
            get {
                return ResourceManager.GetString("GenreNotFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string GridLabel {
            get {
                return ResourceManager.GetString("GridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string InactiveLabel {
            get {
                return ResourceManager.GetString("InactiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred: Quantity must be a integer.
        /// </summary>
        public static string IntegerQuantityErrorMessage {
            get {
                return ResourceManager.GetString("IntegerQuantityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Dashboard.
        /// </summary>
        public static string InventoryDashboardLabel {
            get {
                return ResourceManager.GetString("InventoryDashboardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string ISBNLabel {
            get {
                return ResourceManager.GetString("ISBNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Has Been Removed.
        /// </summary>
        public static string ItemRemovedMessage {
            get {
                return ResourceManager.GetString("ItemRemovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Picture.
        /// </summary>
        public static string LeftPictureLabel {
            get {
                return ResourceManager.GetString("LeftPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Orders.
        /// </summary>
        public static string ManageOrdersMessage {
            get {
                return ResourceManager.GetString("ManageOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Resale Books.
        /// </summary>
        public static string ManageResaleMessage {
            get {
                return ResourceManager.GetString("ManageResaleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your workspace.
        /// </summary>
        public static string ManageWS {
            get {
                return ResourceManager.GetString("ManageWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred: Quantity must be less or equal to the max quantity.
        /// </summary>
        public static string MaxQuantityErrorMessage {
            get {
                return ResourceManager.GetString("MaxQuantityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageLabel {
            get {
                return ResourceManager.GetString("MessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, could not find any relevant books. Try again!.
        /// </summary>
        public static string NoBookFoundMessage {
            get {
                return ResourceManager.GetString("NoBookFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many copies of the book do you have.
        /// </summary>
        public static string NoOfCopiesMessage {
            get {
                return ResourceManager.GetString("NoOfCopiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results Returned.
        /// </summary>
        public static string NoResultsMessage {
            get {
                return ResourceManager.GetString("NoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetailPrice.
        /// </summary>
        public static string OrderDetailPriceCol {
            get {
                return ResourceManager.GetString("OrderDetailPriceCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string OrderIdLabel {
            get {
                return ResourceManager.GetString("OrderIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Info.
        /// </summary>
        public static string OrderInfoLabel {
            get {
                return ResourceManager.GetString("OrderInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string OrdersStatusLabel {
            get {
                return ResourceManager.GetString("OrdersStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred: The order status has changed.
        /// </summary>
        public static string OrderStatusChangeErrorMessage {
            get {
                return ResourceManager.GetString("OrderStatusChangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred: This is already the order status of the order.
        /// </summary>
        public static string OrderStatusNoChangeErrorMessage {
            get {
                return ResourceManager.GetString("OrderStatusNoChangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured: Couldn&apos;t updated order status please try again.
        /// </summary>
        public static string OrderStatusUpdateErrorMessage {
            get {
                return ResourceManager.GetString("OrderStatusUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Payment.
        /// </summary>
        public static string PaymentButton {
            get {
                return ResourceManager.GetString("PaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string PaymentDetailsButton {
            get {
                return ResourceManager.GetString("PaymentDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo content must not contain profanity.
        /// </summary>
        public static string PhotoContentErrorMessage {
            get {
                return ResourceManager.GetString("PhotoContentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo must be of type .jpg or .png or .gif.
        /// </summary>
        public static string PhotoFormatErrorMeessage {
            get {
                return ResourceManager.GetString("PhotoFormatErrorMeessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo must be that of a book.
        /// </summary>
        public static string PhotoTypeErrorMessage {
            get {
                return ResourceManager.GetString("PhotoTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string PublisherLabel {
            get {
                return ResourceManager.GetString("PublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t find in the list ? Add New Publisher.
        /// </summary>
        public static string PublisherNotFoundLabel {
            get {
                return ResourceManager.GetString("PublisherNotFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectButton {
            get {
                return ResourceManager.GetString("RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred: When trying to remove item. Please try again.
        /// </summary>
        public static string RemoveFailErrorMessage {
            get {
                return ResourceManager.GetString("RemoveFailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning removing last item will cancel the order.
        /// </summary>
        public static string RemoveItemWarningMessage {
            get {
                return ResourceManager.GetString("RemoveItemWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Picture.
        /// </summary>
        public static string RightPictureLabel {
            get {
                return ResourceManager.GetString("RightPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChangesButton {
            get {
                return ResourceManager.GetString("SaveChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Books.
        /// </summary>
        public static string SearchBooksMessage {
            get {
                return ResourceManager.GetString("SearchBooksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selet the condition.
        /// </summary>
        public static string SelectConditionLabel {
            get {
                return ResourceManager.GetString("SelectConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the genre.
        /// </summary>
        public static string SelectGenreLabel {
            get {
                return ResourceManager.GetString("SelectGenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the publisher.
        /// </summary>
        public static string SelectPublisherLabel {
            get {
                return ResourceManager.GetString("SelectPublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type.
        /// </summary>
        public static string SelectTypeLabel {
            get {
                return ResourceManager.GetString("SelectTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StateLabel {
            get {
                return ResourceManager.GetString("StateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabular.
        /// </summary>
        public static string TabularLabel {
            get {
                return ResourceManager.GetString("TabularLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Genres.
        /// </summary>
        public static string TopGenresLabel {
            get {
                return ResourceManager.GetString("TopGenresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Publishers.
        /// </summary>
        public static string TopPublishersLabel {
            get {
                return ResourceManager.GetString("TopPublishersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Book Titles.
        /// </summary>
        public static string TopTitlesLabel {
            get {
                return ResourceManager.GetString("TopTitlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Types.
        /// </summary>
        public static string TopTypesLabel {
            get {
                return ResourceManager.GetString("TopTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t find in the list ? Add New BookType.
        /// </summary>
        public static string TypeNotFoundLabel {
            get {
                return ResourceManager.GetString("TypeNotFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated the existing records.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code Label.
        /// </summary>
        public static string ZipCodeLabel {
            get {
                return ResourceManager.GetString("ZipCodeLabel", resourceCulture);
            }
        }
    }
}
